package com.customspace.customproject;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class svsd implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public svsd() {
    }




}